[package]
name = "compilador_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_static = "1.5.0"
regex = "1.12.2"

[[bin]]
name = "compilador_rust"
path = "src/main.rs"

[[bin]]
name = "generador_slr"
path = "src/bin/generador.rs"